name: Arduino
on: [workflow_dispatch, push]

env:
  TARGET: esp32wrover
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        curl https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json --output /home/runner/.arduino15/package_esp32_index.json
        arduino-cli core install -v esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli lib install -v ArduinoJson
        arduino-cli lib install -v --git-url https://github.com/axcap/Esp-GitHub-OTA.git

    - name: Compile Sketch
      run: arduino-cli compile -b esp32:esp32:${{ env.TARGET }} --output-dir build

    - name: Archive Firmware Files
      uses: actions/upload-artifact@v3
      with: 
        path: ./build/*ino.bin

  Release:
    needs: CI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v3

    - name: Release Firmware
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./artifact/*.ino.bin
        generateReleaseNotes: true
        allowUpdates: true