name: Platformio
on: push

env:
  TARGET: nodemcu-32s # Must match the value after colon in platformio.ini (line 4: [env:nodemcu-32s])
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e ${{ env.TARGET }}
    - name: Archive Firmware Files
      uses: actions/upload-artifact@v3
      with: 
        name: esp8266-firmware
        path: .pio/build/${{ env.TARGET }}/firmware.bin

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v3
      with:
        path: release
    - name: Release Firmware
      uses: ncipollo/release-action@v1
      with:
        artifacts: release/*/firmware.bin
        generateReleaseNotes: true
        allowUpdates: true