name: Platformio
on: push

env:
  TARGET: nodemcu-32s # Must match the value after colon in platformio.ini (line 4: [env:nodemcu-32s])
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "data"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      # Only runs if all of the files exists
      run: echo All files exists!

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run -e ${{ env.TARGET }}
    - name: Archive Firmware
      uses: actions/upload-artifact@v3
      with: 
        name: esp32-firmware
        path: .pio/build/${{ env.TARGET }}/firmware.bin

    - name: Compile Filesystem
      run: pio run --target buildfs
    - name: Archive Filesystem
      uses: actions/upload-artifact@v3
      with: 
        name: esp32-filesystem
        path: .pio/build/${{ env.TARGET }}/littlefs.bin

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v3
      with:
        path: release

    - name: Release Firmware
      uses: ncipollo/release-action@v1
      with:
        artifacts: release/*/firmware.bin
        generateReleaseNotes: true
        allowUpdates: true
    - name: Release Filesystem
      uses: ncipollo/release-action@v1
      with:
        artifacts: release/*/littlefs.bin
        generateReleaseNotes: true
        allowUpdates: true